## Olist Notebook

In [2]:
import os
import sys
import numpy as np
import pandas as pd
import psycopg2
import matplotlib.pyplot as plt

In [ ]:
def fill_nulls(df, df_csv):
    df = df.fillna('nill')
    df.to_csv(f'{data_dir}/clean/{df_csv}', index=False)

data_dir = '../data'

reviews = pd.read_csv(f'{data_dir}/order_reviews_dataset.csv')
fill_nulls(reviews, 'order_reviews_dataset.csv')

# NOTE
## codes below this cell were not used

In [2]:
db_host='localhost'
db_name='olist_db'
db_user='olistuser'
db_pass='olistpass'

In [3]:
def connect_to_database():
    """Establish a connection to the PostgreSQL database."""
    try:
        connection = psycopg2.connect(
            dbname=db_name,
            user=db_user,
            password=db_pass,
            host=db_host
        )
        return connection
    except Error as e:
        print(f"Error connecting to database: {e}")
        return None
    
connection = connect_to_database()

In [14]:
data_dir = '../data'
os.listdir(data_dir)
if os.path.isdir(f'{data_dir}/clean') != True:
    os.mkdir(f'{data_dir}/clean')

In [15]:
reviews = pd.read_csv(f'{data_dir}/order_reviews_dataset.csv')

In [16]:
reviews['review_comment_title'].isna().sum()

88285

In [8]:
for col in reviews.columns:
    if reviews[f'{col}'].isnull().sum() / len(reviews) >= 0.5:
        reviews = reviews.drop(columns=f'{col}')
reviews.to_csv(f'{data_dir}/clean/order_reviews_dataset.csv')

In [20]:
reviews

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,nill,nill,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,nill,nill,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,nill,nill,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,nill,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,nill,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53
...,...,...,...,...,...,...,...
99995,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,nill,nill,2017-12-09 00:00:00,2017-12-11 20:06:42
99996,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,nill,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43
99997,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,nill,nill,2018-07-01 00:00:00,2018-07-02 12:59:13
99998,be360f18f5df1e0541061c87021e6d93,f8bd3f2000c28c5342fedeb5e50f2e75,1,nill,Solicitei a compra de uma capa de retrovisor c...,2017-12-15 00:00:00,2017-12-16 01:29:43
99999,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,nill,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

In [68]:
def insert_order_reviews(connection, df):
    """Insert data into the order_reviews table."""
    try:
        cursor = connection.cursor()
        insert_query = """
            INSERT INTO olist.order_reviews (
                review_id,
                order_id,
                review_score,
                review_creation_date,
                review_answer_timestamp
            ) VALUES (
                %s, %s, %s, %s, %s
            )
        """
        for index, row in df.iterrows():
            review_data = (
                row['review_id'],
                row['order_id'],
                row['review_score'],
                row['review_creation_date'],
                row['review_answer_timestamp']
            )
            cursor.execute(insert_query, review_data)
        connection.commit()
        print("Order reviews inserted successfully.")
    except Error as e:
        print(f"Error inserting order reviews: {e}")
        connection.rollback()
connect_to_database()       
insert_order_reviews(connection, reviews)

Order reviews inserted successfully.

In [70]:
# script

import os
import sys
import numpy as np
import pandas as pd
import psycopg2
import matplotlib.pyplot as plt


db_host='localhost'
db_name='olist_db'
db_user='olistuser'
db_pass='olistpass'

data_dir = '../data'

def clean():
    for col in reviews.columns:
        if reviews[f'{col}'].isnull().sum() / len(reviews) >= 0.5:
            reviews = reviews.drop(columns=f'{col}')
    reviews.to_csv(f'{data_dir}/clean/olist_order_reviews_dataset.csv')

def connect_to_database():
    """Establish a connection to the PostgreSQL database."""
    try:
        connection = psycopg2.connect(
            dbname=db_name,
            user=db_user,
            password=db_pass,
            host=db_host
        )
        return connection
    except Error as e:
        print(f"Error connecting to database: {e}")
        return None
    
    
def insert_order_reviews(connection, df):
    """Insert data into the order_reviews table."""
    try:
        cursor = connection.cursor()
        insert_query = """
            INSERT INTO olist.order_reviews (
                review_id,
                order_id,
                review_score,
                review_creation_date,
                review_answer_timestamp
            ) VALUES (
                %s, %s, %s, %s, %s
            )
        """
        for index, row in df.iterrows():
            review_data = (
                row['review_id'],
                row['order_id'],
                row['review_score'],
                row['review_creation_date'],
                row['review_answer_timestamp']
            )
            cursor.execute(insert_query, review_data)
        connection.commit()
        print("Order reviews inserted successfully.")
    except Error as e:
        print(f"Error inserting order reviews: {e}")
        connection.rollback()

    

def main():
    db_host='localhost'
    db_name='olist_db'
    db_user='olistuser'
    db_pass='olistpass'

    data_dir = '../data'
    
    connection = connect_to_database()
    insert_order_reviews(connection, reviews)